import { Event, Partner, Participant, Stats, User } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    name: 'Admin Utilisateur',
    email: 'admin@culture-congo.org',
    role: 'admin',
    avatar: 'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
  {
    id: '2',
    name: 'Marie Organisateur',
    email: 'organisateur@culture-congo.org',
    role: 'organizer',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
  {
    id: '3',
    name: 'Jean Public',
    email: 'public@example.com',
    role: 'public',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=100',
  },
];

export const MOCK_PARTNERS: Partner[] = [
  {
    id: '1',
    name: 'Ministère de la Culture',
    logo: 'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=100',
    website: 'https://culture.gouv.cg',
  },
  {
    id: '2',
    name: 'Festival International de Brazzaville',
    logo: 'https://images.pexels.com/photos/3944109/pexels-photo-3944109.jpeg?auto=compress&cs=tinysrgb&w=100',
    website: 'https://festivalbrazza.org',
  },
  {
    id: '3',
    name: 'Fondation Arts du Congo',
    logo: 'https://images.pexels.com/photos/5083215/pexels-photo-5083215.jpeg?auto=compress&cs=tinysrgb&w=100',
    website: 'https://artscongo.org',
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: 'Festival de Musique Traditionnelle',
    description: 'Un festival célébrant la riche tradition musicale de toutes les régions du Congo, avec des performances de groupes locaux et internationaux.',
    shortDescription: 'Célébration de la musique traditionnelle congolaise',
    startDate: '2025-06-15T10:00:00',
    endDate: '2025-06-18T22:00:00',
    location: 'Place de la Liberté, Brazzaville',
    image: 'https://images.pexels.com/photos/3593865/pexels-photo-3593865.jpeg?auto=compress&cs=tinysrgb&w=1280',
    capacity: 5000,
    registeredCount: 3200,
    category: 'music',
    status: 'upcoming',
    organizers: ['2'],
    partners: [MOCK_PARTNERS[0], MOCK_PARTNERS[1]],
    isPublished: true,
    isFeatured: true,
    ticketPrice: 5000,
    ticketCurrency: 'XAF',
  },
  {
    id: '2',
    title: 'Exposition d\'Art Contemporain',
    description: 'Découvrez les œuvres des artistes contemporains congolais qui explorent des thèmes modernes tout en s\'inspirant de l\'héritage culturel riche du pays.',
    shortDescription: 'Artistes contemporains congolais en exposition',
    startDate: '2025-07-10T09:00:00',
    endDate: '2025-08-10T18:00:00',
    location: 'Musée National, Brazzaville',
    image: 'https://images.pexels.com/photos/1509534/pexels-photo-1509534.jpeg?auto=compress&cs=tinysrgb&w=1280',
    capacity: 1000,
    registeredCount: 450,
    category: 'art',
    status: 'upcoming',
    organizers: ['2'],
    partners: [MOCK_PARTNERS[2]],
    isPublished: true,
    isFeatured: false,
    ticketPrice: 2000,
    ticketCurrency: 'XAF',
  },
  {
    id: '3',
    title: 'Festival International de Danse',
    description: 'Un événement qui réunit des danseurs du monde entier pour célébrer les traditions de danse africaine et contemporaine avec des ateliers et des performances.',
    shortDescription: 'Célébration internationale de la danse africaine',
    startDate: '2025-05-20T14:00:00',
    endDate: '2025-05-25T23:00:00',
    location: 'Stade Alphonse Massamba-Débat, Brazzaville',
    image: 'https://images.pexels.com/photos/1405816/pexels-photo-1405816.jpeg?auto=compress&cs=tinysrgb&w=1280',
    capacity: 3000,
    registeredCount: 2800,
    category: 'dance',
    status: 'completed',
    organizers: ['2'],
    partners: [MOCK_PARTNERS[0], MOCK_PARTNERS[1], MOCK_PARTNERS[2]],
    isPublished: true,
    isFeatured: false,
  },
  {
    id: '4',
    title: 'Atelier de Création Théâtrale',
    description: 'Un atelier intensif de trois jours dirigé par des professionnels du théâtre pour développer les talents des jeunes acteurs congolais.',
    shortDescription: 'Formation théâtrale pour jeunes talents',
    startDate: '2025-09-05T09:00:00',
    endDate: '2025-09-07T17:00:00',
    location: 'Centre Culturel Jean-Baptiste Tati Loutard, Pointe-Noire',
    image: 'https://images.pexels.com/photos/713149/pexels-photo-713149.jpeg?auto=compress&cs=tinysrgb&w=1280',
    capacity: 50,
    registeredCount: 32,
    category: 'workshop',
    status: 'upcoming',
    organizers: ['2'],
    partners: [MOCK_PARTNERS[2]],
    isPublished: true,
    isFeatured: false,
    ticketPrice: 10000,
    ticketCurrency: 'XAF',
  },
  {
    id: '5',
    title: 'Conférence sur le Patrimoine Culturel',
    description: 'Une série de conférences et de discussions sur la préservation et la promotion du patrimoine culturel congolais à l\'ère du numérique.',
    shortDescription: 'Discussions sur la préservation du patrimoine',
    startDate: '2025-08-12T10:00:00',
    endDate: '2025-08-14T16:00:00',
    location: 'Université Marien Ngouabi, Brazzaville',
    image: 'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=1280',
    capacity: 200,
    registeredCount: 150,
    category: 'conference',
    status: 'upcoming',
    organizers: ['2'],
    partners: [MOCK_PARTNERS[0]],
    isPublished: true,
    isFeatured: true,
    ticketPrice: 0,
    ticketCurrency: 'XAF',
  },
];

export const MOCK_PARTICIPANTS: Participant[] = [
  {
    id: '1',
    name: 'Sophie Makosso',
    email: 'sophie@example.com',
    phone: '+242 06 123 4567',
    eventId: '1',
    status: 'confirmed',
    registrationDate: '2025-05-10T14:23:00',
    ticketType: 'standard',
  },
  {
    id: '2',
    name: 'Pascal Moukala',
    email: 'pascal@example.com',
    phone: '+242 05 987 6543',
    eventId: '1',
    status: 'confirmed',
    registrationDate: '2025-05-12T09:45:00',
    ticketType: 'vip',
  },
  {
    id: '3',
    name: 'Claire Ndoulou',
    email: 'claire@example.com',
    phone: '+242 06 555 7777',
    eventId: '2',
    status: 'pending',
    registrationDate: '2025-06-20T16:30:00',
    ticketType: 'standard',
  },
  {
    id: '4',
    name: 'Antoine Moussa',
    email: 'antoine@example.com',
    phone: '+242 05 333 2222',
    eventId: '3',
    status: 'confirmed',
    registrationDate: '2025-04-15T11:20:00',
    ticketType: 'standard',
  },
  {
    id: '5',
    name: 'Marielle Koumba',
    email: 'marielle@example.com',
    phone: '+242 06 777 8888',
    eventId: '4',
    status: 'confirmed',
    registrationDate: '2025-08-01T10:15:00',
    ticketType: 'workshop',
  },
];

export const MOCK_STATS: Stats = {
  totalEvents: 12,
  upcomingEvents: 8,
  totalParticipants: 4850,
  eventsByCategory: {
    music: 4,
    dance: 2,
    theater: 1,
    art: 2,
    festival: 2,
    workshop: 1,
    conference: 0,
    other: 0,
  },
  participantsTrend: [
    { month: 'Jan', count: 320 },
    { month: 'Feb', count: 450 },
    { month: 'Mar', count: 580 },
    { month: 'Apr', count: 620 },
    { month: 'May', count: 750 },
    { month: 'Jun', count: 840 },
    { month: 'Jul', count: 920 },
    { month: 'Aug', count: 370 },
  ],
};